@startuml
actor Usuario
activate UsuarioController
activate UsuarioService
activate UsuarioRepository
database MongoDB

title Eliminar un usuario existente en la base

Usuario -> UsuarioController: eliminarUsuario

UsuarioController -> UsuarioService: eliminarUsuario

UsuarioService -> UsuarioService: validarEmail

UsuarioService -> UsuarioRepository: obtenerUsuarioByEmail

UsuarioRepository -> MongoDB: obtenerUsuarioByEmail

MongoDB -> UsuarioRepository: <<usuario encontrado>>

UsuarioRepository -> UsuarioService: <<usuario encontrado>>

UsuarioService -> UsuarioService: ponerUsuarioComoBorrado

UsuarioService -> UsuarioRepository: actualizarUsuario

UsuarioRepository -> MongoDB: actualizarUsuario


legend
<b>ESCENARIO:</b> Borrado logico de un usuario existente

<b>COMO</b> usuario de Libre Mercado 
<b>QUIERO</b> poder desenrolarme de la aplicacion
<b>PARA</b> que ya no se pueda transaccionar con mi usuario
end legend

@enduml